spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5499/tickets_db
    username: julianfas20
    password: Master1973
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  pattern:
    dateformat: "hh:mm"
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE